In [2]:
import pandas as pd

In [8]:
workdir = "C:\\Users\\ryo.kusaba\\Documents\\work\\2017\\11\\1113"

In [9]:
fmdm = "targetsystem_AAP.txt"

In [10]:
fplm = "mp_region_AAP.csv"

In [11]:
mdmdf = pd.read_csv(workdir + "/" + fmdm, dtype='object', sep='\t')

In [12]:
plmdf = pd.read_csv(workdir + "/" + fplm, dtype='object', header=1)

In [13]:
plmdf.iloc[:10]

  item_trading_code color_code md_approval mp_region
0          1011A002        002        true       AAP
1          1011A002        020        true       AAP
2          1011A002        400        true       AAP
3          1011A002        401        true       AAP
4          1011A006        001        true       AAP
5          1011A006        020        true       AAP
6          1011A007        400        true       AAP
7          1011A008        002        true       AAP
8          1011A008        020        true       AAP
9          1011A008        400        true       AAP

In [14]:
mdmdf_AAP = mdmdf[['Item code', 'ColorID','Target System']][mdmdf['Target System'] =='AAP']

In [15]:
plmdf = plmdf.rename(columns={'item_trading_code':'Item code','color_code':'ColorID','mp_region':'Target System'})

In [16]:
plmdf.columns

Index(['Item code', 'ColorID', 'md_approval', 'Target System'], dtype='object')

In [17]:
merge = pd.merge(plmdf, mdmdf_AAP, how='outer', on=['Item code','ColorID'])

In [18]:
merge.to_csv(workdir + "/" + "merge.txt", index=False, encoding='utf-8', sep='\t')

In [19]:
merge.iloc[:10]

  Item code ColorID md_approval Target System_x Target System_y
0  1011A002     002        true             AAP             AAP
1  1011A002     020        true             AAP             AAP
2  1011A002     400        true             AAP             AAP
3  1011A002     401        true             AAP             AAP
4  1011A006     001        true             AAP             AAP
5  1011A006     020        true             AAP             AAP
6  1011A007     400        true             AAP             AAP
7  1011A008     002        true             AAP             AAP
8  1011A008     020        true             AAP             AAP
9  1011A008     400        true             AAP             AAP

In [20]:
import numpy as np

In [22]:
merge[merge['Target System_y'].isnull()]

    Item code ColorID md_approval Target System_x Target System_y
254  1183A039     250        true             AAP             NaN
255  1183A039     251        true             AAP             NaN
279  1183A078     020        true             AAP             NaN
312  1184A001     250        true             AAP             NaN
313  1184A001     400        true             AAP             NaN
315  1184A002     250        true             AAP             NaN
316  1184A002     400        true             AAP             NaN
317  1191A007     100        true             AAP             NaN
325  1192A006     500        true             AAP             NaN
338  1193A006     001        true             AAP             NaN
360  1193A059     100        true             AAP             NaN
363  1193A071     001        true             AAP             NaN
364  1193A071     100        true             AAP             NaN
367  1193A071     103        true             AAP             NaN
374  1193A095     100        true             AAP             NaN
375  1193A095     102        true             AAP             NaN
376  1193A098     001        true             AAP             NaN
377  1193A098     100        true             AAP             NaN
382  1193A102     020        true             AAP             NaN
390  1193A133     020        true             AAP             NaN
391  1193A133     300        true             AAP             NaN
397  1194A006     100        true             AAP             NaN
398  1203A003     020        true             AAP             NaN
399  1203A003     100        true             AAP             NaN
571  2191A002     001        true             AAP             NaN
572  2191A002     020        true             AAP             NaN
581  2191A007     001        true             AAP             NaN
582  2191A007     400        true             AAP             NaN
592  2191A015     001        true             AAP             NaN
593  2191A016     001        true             AAP             NaN
594  2191A016     020        true             AAP             NaN
595  2191A016     100        true             AAP             NaN
601  2191A019     001        true             AAP             NaN
602  2191A019     020        true             AAP             NaN
603  2191A019     100        true             AAP             NaN
607  2191A023     250        true             AAP             NaN
608  2191A024     250        true             AAP             NaN
615  2191A035     001        true             AAP             NaN
616  2191A037     400        true             AAP             NaN
617  2191A037     600        true             AAP             NaN
628  2191A043     001        true             AAP             NaN
629  2191A043     020        true             AAP             NaN
630  2191A045     001        true             AAP             NaN
631  2191A045     020        true             AAP             NaN
639  2192A004     001        true             AAP             NaN
640  2192A005     001        true             AAP             NaN
641  2192A005     100        true             AAP             NaN
642  2192A005     400        true             AAP             NaN
643  2192A006     001        true             AAP             NaN
691  3191A011     401        true             AAP             NaN
705  3193A001     001        true             AAP             NaN
706  3193A001     400        true             AAP             NaN
782     HN7A0     001        true             AAP             NaN